server:
  port: 8084
spring:
  security:
    user:
      name: user
      password: PasswordEncoder.encode(password)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordering2
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  file:
    name: logs/app.log
  level:
    root: info